apiVersion: v1
kind: Service
metadata:
  name: pokestats-frontend
spec:
  selector:
    app: pokestats
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  clusterIP: 10.0.171.239
  type: LoadBalancer
status:
  loadBalancer:
    ingress:
    - ip: 192.0.2.127
